[mypy]
mypy_path = stubs

# Your current good setting
check_untyped_defs = True
disallow_any_explicit = True

; # Require type hints for all functions and methods
; disallow_untyped_defs = True
disallow_incomplete_defs = True

; # Prevent untyped functions from being called from typed ones
; disallow_untyped_calls = True

# Disallow using variables with 'Any' type in generics (e.g., list[Any])
disallow_any_generics = True

# Warnings for code health and safety
warn_return_any = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_unused_configs = True

# Require Explicit Optionals (e.g., Optional[int] instead of just int = None)
no_implicit_optional = True
strict_optional = True
