# pylint: disable=unused-argument
from collections.abc import Iterator, Sequence

def choice(
    a: range | Sequence[int],
    *,
    size: int,
    replace: bool = ...,
) -> _IntArrayLike: ...

def uniform(low: float, high: float, *, size: int) -> _FloatArrayLike: ...
def pareto(a: float, *, size: int) -> _NumericArrayLike: ...
def lognormal(mean: float, sigma: float, *, size: int) -> _FloatArrayLike: ...

class _IntArrayLike:
    def __iter__(self) -> Iterator[int]: ...

class _FloatArrayLike:
    def __iter__(self) -> Iterator[float]: ...

class _NumericArrayLike:
    def __iter__(self) -> Iterator[float]: ...
    def __mul__(self, other: int | float) -> _FloatArrayLike: ...
    def __rmul__(self, other: int | float) -> _FloatArrayLike: ...
