JOINMARKET_COINJOIN_AMOUNT_SATS = 40000
JOINMARKET_COUNTERPARTIES = 4
JOINMARKET_MAKER_MIN_SIZE_SATS = 30000
JOINMARKET_ROUND_TIMEOUT_BLOCKS = 180
JOINMARKET_FINAL_SETTLE_BLOCKS = 1
JOINMARKET_LOOP_SLEEP_SECONDS = 1
JOINMARKET_DISTRIBUTOR_RPC_WALLET = "jm_wallet_distributor"
