# containers/emulator-manager/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: emulation-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: emulation-manager
subjects:
  - kind: ServiceAccount
    name: emulation-manager
