from collections.abc import Sequence

class WSClient:
    def is_open(self) -> bool: ...
    def update(self, *, timeout: int) -> None: ...
    def peek_stdout(self) -> bool: ...
    def read_stdout(self) -> str: ...
    def peek_stderr(self) -> bool: ...
    def read_stderr(self) -> str: ...
    def write_stdin(self, data: bytes) -> None: ...
    def close(self) -> None: ...

def stream(
    func: object,
    name: str,
    namespace: str,
    *,
    command: Sequence[str],
    stderr: bool,
    stdin: bool,
    stdout: bool,
    tty: bool,
    _preload_content: bool,
) -> WSClient: ...
