from collections.abc import Sequence

class WSClient:
    def is_open(self) -> bool: ...
    def update(self, *, _timeout: int) -> None: ...
    def peek_stdout(self) -> bool: ...
    def read_stdout(self) -> str: ...
    def peek_stderr(self) -> bool: ...
    def read_stderr(self) -> str: ...
    def write_stdin(self, _data: bytes) -> None: ...
    def close(self) -> None: ...

def stream(
    _func: object,
    _name: str,
    _namespace: str,
    *,
    _command: Sequence[str],
    _stderr: bool,
    _stdin: bool,
    _stdout: bool,
    _tty: bool,
    _preload_content: bool,
) -> WSClient: ...
